### PR TITLE
_cameraController intializer takePicture

### PR DESCRIPTION
**Pull request by imasif**
fixed camera initialization await before takePicture method being called, other wise the following exception was thrown:
`Exception has occurred. CameraException (CameraException(error, CaptureRequest contains unconfigured Input/Output Surface!))`

Fixes for issue: https://github.com/rushio-consulting/flutter_camera_ml_vision/issues/62#

### CODE REVIEW

**Review by bmabir17 — APPROVED** [review]
I also faced the similar issue #62  . This solution has worked for me.

**Comment by kevin-sakemaer** [comment]
Does it fix your issues ?
That seems pretty strange since `_cameraController.initialize()` is called in the start function so as soon as you see the stream on image it should not be necessary to add this call.

**Comment by jaumard** [comment]
I agree with @Kleak, this mean that you're calling takePicture too soon, can you confirm this just by waiting that the camera is Streaming images and then call takePicture ? It should worked normally

**Comment by imasif** [comment]
Without waiting to initilialize the takePicture method doesnt work

**Comment by imasif** [comment]
I tried this without using the initializer:
      

```
await _scanKey.currentState.stop();
        new Timer(const Duration(seconds: 5), ()async{
          await _scanKey.currentState.takePicture(path);
          await _scanKey.currentState.start();
        });

```

the floowing error is thrown:
`E/MethodChannel#plugins.flutter.io/camera(30245): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/camera(30245): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/camera(30245): 	at android.os.Looper.loop(Looper.java:165)
E/MethodChannel#plugins.flutter.io/camera(30245): 	at android.app.ActivityThread.main(ActivityThread.java:6806)
E/MethodChannel#plugins.flutter.io/camera(30245): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera(30245): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#plugins.flutter.io/camera(30245): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)`

**Comment by jaumard** [comment]
One question, why do you call stop ?? should work without stoping the camera ^^

**Comment by imasif** [comment]
@jaumard can you provide some code working example? I've tried without stop and start, but when I call: `await _scanKey.currentState.takePicture(path);` it always returns 

> Exception has occurred. CameraException (CameraException(error, CaptureRequest contains unconfigured Input/Output Surface!))

**Comment by jaumard** [comment]
I'm closing this one, it's taking care by #97 by exposing directly the camera controller so you have full control if you want/need
Thanks !

**Comment by imasif** [comment]
Thanks ! :)

**Pull request closed without merging**
